name: .NET Core CI

on:
  push:
    branches:
      - development
      - master
  pull_request:
    branches:
      - development
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Check installed .NET SDKs
        run: |
          dotnet --version
          dotnet --list-sdks
          
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          sdk-version: '9.0.x'  # Use the latest .NET 9 SDK

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Build code
        run: dotnet build --configuration Release --no-restore

      - name: Run tests with code coverage
        run: dotnet test --configuration Release --no-build --logger "trx;LogFileName=test-results.trx" --verbosity normal

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: TestResults/
