name: .NET Core CI

on:
  push:
    branches:
      - development
      - master
  pull_request:
    branches:
      - development
      - master
  workflow_dispatch:  # Allows manual trigger via GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install .NET 9 SDK
        run: |
          wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
          sudo bash dotnet-install.sh --version 9.0.202 --install-dir /usr/share/dotnet
          sudo rm -f /usr/bin/dotnet  # Remove any existing symbolic link
          sudo ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet  # Create new symbolic link

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build code
        run: dotnet build --configuration Release --no-restore

      - name: Run tests with code coverage
        run: dotnet test --configuration Release --no-build --logger "trx;LogFileName=test-results.trx" --verbosity normal

      - name: Upload test results
        if: always()  # Always upload test results even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./TestResults/test-results.trx  # Ensure the correct path to test results
